
server:
  servlet:
    contextPath: /auth-service
    session:
      persistent: true
  port: 8098
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.20.255:5434/Hos?serverTimezone=UTC
    username : postgres
    password : root
logging:
  level:
    root: WARN

