server:
  servlet:
    contextPath: /hos-service
    session:
      persistent: true
  port: 8099
spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.23.51:5432/hos?serverTimezone=UTC
    username : postgres
    password : root
  mail:
    host: smtp.gmail.com
    port: 587
    username: tamilarasisk13@gmail.com
    password: bozj uqtm ujwd alsw
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
logging:
  level:
    root: DEBUG

